
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



import GooeyNav from '../components/GooeyNav'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const items = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Table", href: "/dataTable" },
];
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center`}
      >
        {/* Centered fixed nav */}
        <div className="top-0 w-11/12 flex justify-center mt-15">
          <GooeyNav items={items} />
        </div>

        {/* Add top padding to push content below the nav */}
        <main className="w-full pt-15" >  
          {children}
        </main>
      </body>
    </html>
);


}
